[package]
name = "rusty-roads"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Needed until bindgen has the `allowlist_file` feature
css-inline = "0.8"
rutie = "*"
